version: '3.4'

services:
  sqldata:
      image: mcr.microsoft.com/mssql/server:2019-latest
      environment:
          - SA_PASSWORD=Numsey#2022
          - ACCEPT_EULA=Y
      ports:
          - "1450:1433"


  appartmentsystem.api:
    image: ${DOCKER_REGISTRY-}appartmentsystemapi
    build:
      context: .
      dockerfile: AppartmentSystem.Api/Dockerfile

  carsystem.api:
    image: ${DOCKER_REGISTRY-}carsystemapi
    build:
      context: .
      dockerfile: CarSystem.Api/Dockerfile


  schoolsystem.api:
    image: ${DOCKER_REGISTRY-}schoolsystemapi
    build:
      context: .
      dockerfile: SchoolSystem.Api/Dockerfile


  tourismsystem.api:
    image: ${DOCKER_REGISTRY-}tourismsystemapi
    build:
      context: .
      dockerfile: TourismSystem.Api/Dockerfile

